"""accounts added

Revision ID: cfc6419c4e48
Revises: 02a3f8ae232d
Create Date: 2024-04-15 22:52:11.298794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfc6419c4e48'
down_revision = '02a3f8ae232d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pdf_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('subscription')
    op.drop_table('file')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('image_file')
        batch_op.drop_column('pdf_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('image_file', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('bio', mysql.VARCHAR(length=350), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_id')

    op.create_table('file',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('original_filename', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('filename', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bucket', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('subscription',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('subscriber_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('subscribed_to_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscribed_to_id'], ['user.id'], name='subscription_ibfk_2'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], name='subscription_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('account')
    # ### end Alembic commands ###
